/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: ProcessExplorerMessages.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as ProcessExplorerMessages_pb from './ProcessExplorerMessages_pb';
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';


export class ProcessExplorerMessageHandlerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSend = new grpcWeb.MethodDescriptor(
    '/ProcessExplorerMessageHandler/Send',
    grpcWeb.MethodType.UNARY,
    ProcessExplorerMessages_pb.Message,
    google_protobuf_empty_pb.Empty,
    (request: ProcessExplorerMessages_pb.Message) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  send(
    request: ProcessExplorerMessages_pb.Message,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  send(
    request: ProcessExplorerMessages_pb.Message,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  send(
    request: ProcessExplorerMessages_pb.Message,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ProcessExplorerMessageHandler/Send',
        request,
        metadata || {},
        this.methodDescriptorSend,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ProcessExplorerMessageHandler/Send',
    request,
    metadata || {},
    this.methodDescriptorSend);
  }

  methodDescriptorSubscribe = new grpcWeb.MethodDescriptor(
    '/ProcessExplorerMessageHandler/Subscribe',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    ProcessExplorerMessages_pb.Message,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    ProcessExplorerMessages_pb.Message.deserializeBinary
  );

  subscribe(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<ProcessExplorerMessages_pb.Message> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/ProcessExplorerMessageHandler/Subscribe',
      request,
      metadata || {},
      this.methodDescriptorSubscribe);
  }

}

