name: Dependency Submission

on:
  workflow_dispatch:

permissions: 
  contents: read

jobs:
  dependency-submission:
    permissions: 
      id-token: write
      contents: write
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
        node-version: [ '22.x' ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build Components
        run: |
              npm i
              npx lerna run build --stream
              powershell ./build/dotnet-restore.ps1
              powershell ./build/dotnet-build.ps1
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@1874d0f72d77ddf201936b16a90f28b237709753 # v0.0.6
        with:
          detectorsFilter: "NuGetProjectCentric,Npm,NpmLockfile3"
