name: Publish Package to npmjs

on:
  workflow_call:
  
jobs:
  deploy-npm:
    # TODO: revist this workflow to include all packages
    name: Deploy composeui-node-launcher to NPM
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ '18.x' ]
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx lerna run build
      - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish composeui-node-launcher
        run: npm publish
        working-directory: ${{ github.workspace }}/src/shell/js/composeui-node-launcher/
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}