name: Publish Package to npmjs

on:
  workflow_call:
  
jobs:
  deploy-npm:
    name: Deploy packages to NPM
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ '18.x' ]
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx lerna run build
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}