on:
  release:
    types: [ published ]
    branches: [ main ]

  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

name: Release

jobs:
  build:
    uses: ./.github/workflows/continuous-integration.yml
  
  deploy-npm:
    name: Publish Package to npmjs
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: |
             lerna publish --no-private
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
