on:
  release:
    types: [ published ]
    branches: [ main ]

  workflow_call:

permissions:
  contents: read

name: Upload Release Asset

jobs:
  build:
    uses: ./.github/workflows/continuous-integration-prototypes.yml
  upload:
    name: Upload Release Asset
    needs: build
    runs-on: windows-latest
  
    steps:

      # Using shared artifact from build workflow
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: shell-binaries
          path: ${{ github.workspace }}/shell-binaries
    
      - name: Display structure of downloaded files
        run: Get-ChildItem -Recurse
        working-directory: ${{ github.workspace }}/shell-binaries
        
      - name: Compress
        run: Compress-Archive -Path  ${{ github.workspace }}/shell-binaries/* composeui-${{ github.ref_name }}-win32.zip
        
  assets:
      runs-on: windows-latest
      needs: upload
      permissions:
        contents: write
        actions: read
      steps:
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref }} composeui-${{ github.ref_name }}-win32.zip
          
